#ifndef AG_AGGLOBAL_HPP
#define AG_AGGLOBAL_HPP

#define AG_SHARED_IMPORT Q_DECL_IMPORT
#define AG_SHARED_EXPORT Q_DECL_EXPORT

#define AG_NAMESPACE_BEGIN
#define AG_NAMESPACE_END
#define AG_PRIVATE_SECTION_BEGIN(n) {
#define AG_PRIVATE_SECTION_END(n) }

#endif //
